### ISSUE TITLE
Работа с данными

### ISSUE THREAD

**Issue by mariaYunB** [OneBootcamp-1-0/itsdone-1#10]
- [x] Сверстать карточку в разных состояниях (done/not done)
- [x]  Сверстать карточку для канбана
- [x] Сгенерировать данные
- [x] Настроить фильтрацию по колонкам

**Comment by kicumkicum** [comment]
Неделя закончилась, но мы не смогли предоставить релиз/демо/ПР/конечный результат :(

На самом деле ето классика, и таких ситуаций будет много. Но что можно было сделать, чтобы закончить неделю в пятницу с ощущением победы? Вынести незавершенную часть в отдельную задачу, если ето возможно. 

В данном случае у нас есть 4 (на мой взгляд) независимые задачи. И верстку карточки под разные состояния можно было отделить.

У вас может возникнуть WTF - нас же об етом не просили 😄  Все так, но будучи разработчиками, думайте о ваших интересах. А в ваших интересах почувствовать вкус победы и не работать в выходные. Для етого нужно подбирать концы и декомпозировать частично решенные задачи.
