### ISSUE TITLE
План на неделю 14 - 18

### ISSUE THREAD

**Issue by JohnC27** [OneBootcamp-1-0/itsdone-1#14]
- Пн, Кнопки переключения канбан/грид
- Пн, Делать карточку done/notDone
- Вт, Редактирование
- Вт, Перетаскивание карточек
- Ср, Создание новой карточки
  - Отобразить карточку с бойлерплейтом в режиме редактирования
  - Добавить кнопки отменить и сохранить карточку
  - При нажатии на отменить - удалять карточку
  - При нажатии на сохранить - добавить в данные объект с данными карточки, перерисовать дом
- Чт, загрузка данных

**Comment by kicumkicum** [comment]
Во вторник нужно обсудить #16
