### ISSUE TITLE
Нужны уточнения

### ISSUE THREAD

**Issue by mariaYunB** [OneBootcamp-1-0/itsdone-1#27]
Будут ли теги в канбан-отображении
Как считается completed tasks ratio
Какие проценты являются break point для цветов в completed tasks ratio
Какой алгоритм отображения текста под статусами задач в статистике
Какой алгоритм отображения цвета у тегов
Как задавать теги на карточке (инпут/кнопка/etc)
Текстовое описание даты должно быть на русском или на английском (расписание и карточка)

**Comment by o0** [comment]
1. Во всех отображениях, в канбан тоже
2. Процент законченных тасков от незаконченных
3. 50/75
4. Done — больше 75 процентов за период. In progress — меньше 25 процентов задач от общего числа в In Progress. 
5. На усмотрение. Может быть любой фиксированный набор цветов, каждый новый тег раскрашивается в новый цвет. Для простоты можно не синхронизировать цвета тегов между задачами
6. На усмотрение. По нажатию на них в первой итерации ничего не происходит. В последующих нажатие на тег переключает в режим фильтрации по этому тегу. Редактирование набора тегов делается через единственный инпут, теги разделяются пробелами и начинаются с решетки.
7. Весь сайт на английском
