### ISSUE TITLE
План на спринт

### ISSUE THREAD

**Issue by mariaYunB** [OneBootcamp-1-0/itsdone-1#28]
1. - [x] (?) Сервер для данных
8. - [x] (??) Redux
      - [x] Использовать данные сервера через Redux
2. - [x] (!!) Новое отображение доски
3. - [x] (!) Кнопка show completed
4. - [x] (!) Отображение тегов
6. - [x] (!) Редактировать список тегов
      - [x] Добавить инпут для тегов в режиме редактирования карточки
      - [x] Валидация кол-ва тегов(5), кол-ва символов в теге(10)
      - [x] Добавление `#` при сохранении, если её нет
      - [x] Добавление рандомного цвета тегу 
      - [x] Для существующего тега применяется его сохранённый цвет

-----------------------------
7. - [x] (!!) Преобразование даты в слова
5. - [x] (!!) Статистика
6. - [ ] (??) Серверный рендеринг
7. - [ ] (??) Офлайн

**Comment by kicumkicum** [comment]
Уточнения по проекту в #27
