### ISSUE TITLE
Отображение

### ISSUE THREAD

**Issue by mariaYunB** [OneBootcamp-1-0/itsdone-1#43]
1. Высота NewCard на 20px меньше, чем GridCard
2. Теги позиционируются не по макету
3. Кнопки отменить/сохранить остались на русском
4. Если в каком-то из Blocks нет карточек, остаётся title - надо убирать весь блок
----------------------------
 Карточка AddNew жёстко задаётся в блоке No Date, блок остается, даже если нет карточек с NoDate (несмотря на [4.])

**Comment by kicumkicum** [comment]
А почему `question`? Может сразу ставить `bug`? На баги ведь похоже
