### ISSUE TITLE
Не применяются стили к компоненте, при импорте их без css module

### ISSUE THREAD

**Issue by JohnC27** [OneBootcamp-1-0/itsdone-1#8]
Класс добавляется к тегу, но стили на него не вешаются

**Comment by kicumkicum** [comment]
Покажи пожалуйста пример кода. А то что то я не могу смоделировать

**Comment by JohnC27** [comment]
В ветке `bug/styles`, в `App.jsx` класс `.page` вешается, стили не цепляются
